name: Build Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get max semver tag
        id: get_max_semver_tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: dorny/sort-semver@v1
        with:
          extract-version: 'refs/tags/(.*)'
          include: '${{ github.ref }}'

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set Docker tag based on branch or tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "staging" > docker_tag.txt
          elif [[ "${{ github.ref }}" == "refs/tags/${{ steps.get_max_semver_tag.outputs.max }}" ]]; then
            echo "${{ github.ref_name }}" > docker_tag.txt
          else
            echo "${{ github.ref_name }}" > docker_tag.txt
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mentordosnerds/google-calendar-sync:$(cat docker_tag.txt)

      - name: Upload Docker tag as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-tag
          path: docker_tag.txt
