name: Build Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  release:
    types:
      - created
  workflow_dispatch:  # Para acionar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set Docker tag based on branch or tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "staging" > docker_tag.txt
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "${{ github.event.release.tag_name }}" > docker_tag.txt
            echo "latest" > latest.txt
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            echo "${{ github.ref_name }}" > docker_tag.txt
          else
            echo "${{ github.ref_name }}" > docker_tag.txt
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            mentordosnerds/google-calendar-sync:$(cat docker_tag.txt)
            $(if [ -f latest.txt ]; then echo "mentordosnerds/google-calendar-sync:latest"; fi)

      - name: Upload Docker tag as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-tag
          path: docker_tag.txt
