name: Sync Google Calendars

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set Docker tag based on branch or tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::${{ github.ref_name }}"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: coisa/google-calendar-sync:${{ steps.docker_tag.outputs.tag }}

  sync:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - name: Run Docker image
        run: |
          docker run --rm \
            -e EMAIL_SOURCE="${{ secrets.EMAIL_SOURCE }}" \
            -e EMAIL_TARGET="${{ secrets.EMAIL_TARGET }}" \
            -e SOURCE_CALENDAR_ID="${{ secrets.SOURCE_CALENDAR_ID }}" \
            -e TARGET_CALENDAR_ID="${{ secrets.TARGET_CALENDAR_ID }}" \
            -e SOURCE_SERVICE_ACCOUNT_KEY="${{ secrets.SOURCE_SERVICE_ACCOUNT_KEY }}" \
            -e TARGET_SERVICE_ACCOUNT_KEY="${{ secrets.TARGET_SERVICE_ACCOUNT_KEY }}" \
            coisa/google-calendar-sync:latest
